#!/bin/sh
# Checks for errors with black, flake8 and mypy before pushing
# Aborts the push if any of the checks fail

echo "Running pre-push checks..."

echo "Checking for formatting errors with black..."
black . --check
if [ $? -ne 0 ]; then
  echo "black format check failed. Aborting push."
  exit 1
fi

echo "Checking for linting errors with flake8..."
flake8 .
if [ $? -ne 0 ]; then
  echo "flake8 check failed. Aborting push."
  exit 1
fi

echo "Checking for type errors with mypy..."
mypy .
if [ $? -ne 0 ]; then
  echo "mypy check failed. Aborting push."
  exit 1
fi

echo "All checks passed. Pushing..."
